#!/usr/bin/env bash
# Usage: ans completions <command> [arg1 arg2...]

set -e
[ -n "$ANS_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
    ans-help --usage completions >&2
    exit 1
fi

COMMAND_PATH="$(command -v "ans-$COMMAND" || command -v "ans-sh-$COMMAND")"
if grep -i "^\([#%]\|--\|//\) provide ans completions" "$COMMAND_PATH" >/dev/null; then
    shift
    exec "$COMMAND_PATH" --complete "$@"
fi
