#!/usr/bin/env bash
# Summary: Configure the shell environment for ans
# Usage: eval "$(ans init - [<shell>])"

set -e
[ -n "$ANS_DEBUG" ] && set -x

print=""
no_rehash_arg=""
for args in "$@"; do
    if [ "$args" = "-" ]; then
        print=1
        shift
    fi
    if [ "$args" = "--no-rehash" ]; then
        no_rehash_arg="--no-rehash "
        shift
    fi
done

shell="$1"
if [ -z "$shell" ]; then
    shell="$(basename "$SHELL")"
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
    echo "ans: cannot find readlink - are you missing GNU coreutils?" >&2
    exit 1
fi

function resolve_link {
    $READLINK "$1"
}

function abs_dirname {
    local cwd="$(pwd)"
    local path="$1"
    while [ -n "$path" ]; do
        cd "${path%/*}"
        local name="${path##*/}"
        path="$(resolve_link "$name" || true)"
    done
    pwd
    cd "$cwd"
}

root="$(abs_dirname "$0")/.."

if [ -z "$print" ]; then
    case "$shell" in
        bash) profile='~/.bash_profile'            ;;
        zsh)  profile='~/.zshrc'                   ;;
        ksh)  profile='~/.profile'                 ;;
        fish) profile='~/.config/fish/config.fish' ;;
        *)    profile='your profile'               ;;
    esac
    {
        echo "# Load ans automatically by adding"
        echo "# the following to ${profile}:"
        echo
        case "$shell" in
            fish) echo 'status --is-interactive; and source (ans init -|psub)' ;;
            *) echo 'eval "$(ans init -)"' ;;
        esac
        echo
    } >&2
    exit 1
fi

mkdir -p "${ANS_ROOT}/projects"

case "$shell" in
    bash|zsh|fish) echo "source \"$root/completions/ans.${shell}\"" ;;
esac

case "$shell" in
    fish) cat <<EOS
function ans
  set command \$argv[1]
  set -e argv[1]

  command ans "\$command" \$argv
end
EOS
          ;;
    *) cat <<EOS
ans() {
  typeset command
  command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi
  command ans "\$command" "\$@"
}
EOS
       ;;
esac

for project in $(ans-ls-project); do
    PROJECT_ROOT_VALUE=$(echo ${project}_ROOT | tr "[a-z]" "[A-Z]")
    PROJECT_ROOT="${ANS_ROOT}/projects/${project}"
    case "$shell" in
        fish)
            echo "set -x ${PROJECT_ROOT_VALUE} \"${PROJECT_ROOT}\""
            export ${PROJECT_ROOT_VALUE}="${PROJECT_ROOT}"
            ;;
        *)
            echo "export ${PROJECT_ROOT_VALUE}=\"${PROJECT_ROOT}\""
            export ${PROJECT_ROOT_VALUE}="${PROJECT_ROOT}"
            ;;
    esac
done
